### ISSUE TITLE
does not work with several disks

### ISSUE THREAD

**Issue by nick2ld** [kuchel77/diskspace#1]
does not work with several disks, at all shows the data of the first

**Comment by kuchel77** [comment]
Ok, I have fixed the error that didn't change paths from the default "/" (v0.4 release).

If you are running your Home Assistant in a docker, note that unless you have passed through the mounted directory that you want to measure, then this will fail with a Error 2, can't find the directory.

For instance, I have a NAS mounted at /home/user/videos which is then used in my Plex docker container, but it isn't used in my Home Assistant docker container. Because of this, I can't use this technique to figure out the disk space for my NAS. This is a limitation of the docker structure. I will have a look if it is possible otherwise, but I don't think so.

If you aren't using Home Assistant in a docker image, then you should be able to use any of the mount points, however all of my testing systems I am using a docker at the moment.

**Comment by nick2ld** [comment]
> Ok, I have fixed the error that didn't change paths from the default "/" (v0.4 release).
> 
> If you are running your Home Assistant in a docker, note that unless you have passed through the mounted directory that you want to measure, then this will fail with a Error 2, can't find the directory.
> 
> For instance, I have a NAS mounted at /home/user/videos which is then used in my Plex docker container, but it isn't used in my Home Assistant docker container. Because of this, I can't use this technique to figure out the disk space for my NAS. This is a limitation of the docker structure. I will have a look if it is possible otherwise, but I don't think so.
> 
> If you aren't using Home Assistant in a docker image, then you should be able to use any of the mount points, however all of my testing systems I am using a docker at the moment.

just updated.
does not work (
my mount points:
/ usr / share / hassio / share / flash
/ usr / share / hassio / share / D1
etc.
  - platform: diskspace
    name: Disk 1
    path: "/usr/share/hassio/share/D1"
    unit_of_measure: "GB"

**Comment by nick2ld** [comment]
еще попробовал относительные пути
такие как:
/share/D1
etc.
from the command line they are available

**Comment by kuchel77** [comment]
If you can use a terminal to get the output of 

**df**

from inside the docker container, rather than the host.

If you post that here, that will help me figure out the issue. My guess it that the docker changes the mount point for each container. 

Based on the comment above, I would guess that the mount points get changed. 

Try

```yaml
platform: diskspace
name: Disk 1
path: "/share/D1"
unit_of_measure: "GB"
```

**Comment by nick2ld** [comment]
> If you can use a terminal to get the output of
> 
> **df**
> 
> from inside the docker container, rather than the host.
> 
> If you post that here, that will help me figure out the issue. My guess it that the docker changes the mount point for each container.
> 
> Based on the comment above, I would guess that the mount points get changed.
> 
> Try
> 
> ```yaml
> platform: diskspace
> name: Disk 1
> path: "/share/D1"
> unit_of_measure: "GB"
> ```
^ tried it.
here is the output of the command df

Filesystem           1K-blocks      Used Available Use% Mounted on
none                  27679772  11972008  14278672  46% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                   984612         0    984612   0% /sys/fs/cgroup
shm                      65536         0     65536   0% /dev/shm
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /sbin/docker-init
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /config
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /share
/dev/mmcblk2          29703044     45084  28126056   0% /share/flash
/dev/sda1            960380540 551845712 408518444  57% /share/Rescue
/dev/sdb1            479669932    329492 479324056   0% /share/D1
/dev/sdc1            479669932 254615956 225037592  53% /share/D2
//192.168.1.82/Volume_1
                     1920802736 1432424768 488377968  75% /share/NAS
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /ssl
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /etc/resolv.conf
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /etc/hostname
/dev/mapper/NAS--vg-root
                      27679772  11972008  14278672  46% /etc/hosts

**Comment by kuchel77** [comment]
```
- platform: diskspace
  name: Disk 1
  path: "/share/D1"
  unit_of_measure: "GB"
```

```
- platform: diskspace
  name: Disk 2
  path: "/share/flash"
  unit_of_measure: "GB"
```

```
- platform: diskspace
  name: Disk 3
  path: "/share/NAS"
  unit_of_measure: "GB"
```

Should get you all of the disk space data for those three drives. The last part of the command shows how the hardware has been mapped in the docker image, and that is the path you wan to use.

**Comment by nick2ld** [comment]
Here is my config:
 
 - platform: diskspace
    name: Main
    path: "/"
    unit_of_measure: "GB"
  - platform: diskspace
    name: Flash
    path: "/share/flash"
    unit_of_measure: "GB"
  - platform: diskspace
    name: Disk 1
    path: "/share/D1"
    unit_of_measure: "GB"
  - platform: diskspace
    name: Disk 2
    path: "/share/D2/"
    unit_of_measure: "GB"
  - platform: diskspace
    name: Disk NAS
    path: "/share/NAS"
    unit_of_measure: "GB"
  - platform: diskspace
    name: Disk Rescue
    path: "/share/Rescue"
    unit_of_measure: "GB"

and that's what I get:
https://www.dropbox.com/sh/dsekw35qu8usj8k/AADeHdZyLRs1Ra22ob2fB1-6a?dl=0&preview=screenshot-192.168.1.128_8123-2020.02.24-13_44_03.png

**Comment by kuchel77** [comment]
sensor | state | attributes
-- | -- | --
sensor.disk_space_cgroup | 4 | total: 4 used: 0 free: 4 percentage_free: 100 unit_of_measurement: GB friendly_name: Disk Space cgroup icon: mdi:harddisk
sensor.disk_space_init | 0 | total: 126 used: 126 free: 0 percentage_free: 0 unit_of_measurement: MB friendly_name: Disk Space init icon: mdi:harddisk
sensor.disk_space_main_disk | 367 | total: 490 used: 98 free: 367 percentage_free: 74.8 unit_of_measurement: GB friendly_name: Disk Space Main Disk icon: mdi:harddisk

```yaml
- platform: diskspace
  name: cgroup
  path: "/sys/fs/cgroup"
  unit_of_measure: "GB"
- platform: diskspace
  name: init
  path: "/dev/init"
  unit_of_measure: "MB"
- platform: diskspace
  name: Main Disk
  path: "/"
  unit_of_measure: "GB"
```

This is what I am getting again. My only thought is that something either hasn't updated properly from Github, in which case I will try another release tonight to see if it fixes it, or it hadn't updated as yet in Home Assistant. On my local development instance, it would take a little bit to update the first time it was run, but after that, it was perfect.
