### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'diskspace'

### ISSUE THREAD

**Issue by SmartHomeFanatic** [kuchel77/diskspace#7]
No 'version' key in the manifest file for custom integration 'diskspace'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'diskspace'

Any plans on updating this?

**Comment by kuchel77** [comment]
Sorry, I have been moving systems and I hadn't readded this into my integrations yet so I hadn't been seeing the errors. This should now be fixed.

**Comment by SmartHomeFanatic** [comment]
Thanks for your fast response!
